### ISSUE TITLE
`core.async` interop?

### ISSUE THREAD

**Issue by loganpowell** [athos/kitchen-async#2]
Getting excited to use this library, but was hoping to find some docs on the interop syntax for js/Promise -> core.async. I noticed the library is proposing to do this. Any thoughts of when?

**Comment by athos** [comment]
Hi, @loganpowell. Thank you for trying this library!

As for core.async integration, the conversion from core.async channels to Promises has already been done (but not documented yet). Once we do `(:require kitchen-async.promise.from-channel)`, we can use a core.async channel as if it were a Promise in the kitchen-async macros:

```clj
(ns example.core
  (:require [clojure.core.async :as a]
            [kitchen-async.promise :as p]
            kitchen-async.promise.from-channel))

(def ch (a/chan))

(p/let [x ch]
  (println x))

(a/put! ch 42) ;; prints 42
```

As for the inverse conversion (Promises -> core.async channels), on the other hand, I don't have any concrete plan for that at the moment. At least after v0.1.0 release?

**Comment by loganpowell** [comment]
Hi @athos thank you for the update! Yes, I'll look forward to the promises->chan release!
